// Jupyter Notebook structure for Google Colab using pure Hugging Face Models
export const generateColabNotebook = () => {
  return {
    nbformat: 4,
    nbformat_minor: 0,
    metadata: {
      colab: {
        name: "CarPark_Direct_LicensePlate_HF_GoogleColab.ipynb",
        provenance: [],
        toc_visible: true,
      },
      kernelspec: {
        name: "python3",
        display_name: "Python 3",
      },
      language_info: {
        name: "python",
      },
    },
    cells: [
      {
        cell_type: "markdown",
        metadata: { id: "intro_md" },
        source: [
          "# 🚗 CarPark Direct: License Plate OCR & Google Chat Notifier\n",
          "### Powered by Hugging Face Vision Transformers (`microsoft/trocr-base-printed`) & Google Sheets\n",
          "\n",
          "**Objective:**\n",
          "1. **Capture or upload** a car photo in your company parking bay.\n",
          "2. **Extract the registration plate** using **Hugging Face's official TrOCR Transformer model** (`transformers.VisionEncoderDecoderModel`).\n",
          "3. **Query the Google Sheets Employee Parking Registry** (Name, Google Email, Bay #, Phone).\n",
          "4. **Generate a 1-click direct Google Chat message** (`https://chat.google.com/dm/{email}`) or send an automated Webhook.\n",
        ],
      },
      {
        cell_type: "markdown",
        metadata: { id: "step1_md" },
        source: [
          "## Step 1: Install Hugging Face Transformers & PyTorch\n",
          "Installs the Hugging Face `transformers` library, PyTorch vision tools, `gspread` for Google Sheets, and image utilities.",
        ],
      },
      {
        cell_type: "code",
        metadata: { id: "step1_code" },
        execution_count: null,
        outputs: [],
        source: [
          "# Install Hugging Face ecosystem and dependencies (including sentencepiece & protobuf for tokenizer)\n",
          "!pip install -q \"transformers[sentencepiece]\" sentencepiece protobuf tiktoken torch torchvision pillow requests pandas gspread google-auth opencv-python-headless\n",
          "\n",
          "print('✅ Hugging Face and vision dependencies successfully installed in Google Colab!')\n",
        ],
      },
      {
        cell_type: "markdown",
        metadata: { id: "step2_md" },
        source: [
          "## Step 2: Load Hugging Face TrOCR Model (`microsoft/trocr-base-printed`)\n",
          "Loads the pretrained Hugging Face TrOCR (Transformer Optical Character Recognition) model and processor with GPU acceleration.",
        ],
      },
      {
        cell_type: "code",
        metadata: { id: "step2_code" },
        execution_count: null,
        outputs: [],
        source: [
          "import re\n",
          "import torch\n",
          "import numpy as np\n",
          "import pandas as pd\n",
          "import requests\n",
          "from PIL import Image\n",
          "from transformers import AutoImageProcessor, AutoTokenizer, TrOCRProcessor, VisionEncoderDecoderModel\n",
          "\n",
          "# 1. Select device (Colab GPU or CPU)\n",
          "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
          "print(f'Using device: {device}')\n",
          "\n",
          "# 2. Load Hugging Face TrOCR model & processor\n",
          "# Note: microsoft/trocr-base-printed uses the RoBERTa-large vocabulary.\n",
          "# Loading AutoTokenizer from 'roberta-large' provides pre-built 'tokenizer.json',\n",
          "# completely bypassing SentencePiece/Tiktoken requirement in Python 3.13!\n",
          "HF_MODEL_NAME = 'microsoft/trocr-base-printed'\n",
          "print(f'Loading Hugging Face model ({HF_MODEL_NAME})...')\n",
          "\n",
          "image_processor = AutoImageProcessor.from_pretrained(HF_MODEL_NAME)\n",
          "try:\n",
          "    tokenizer = AutoTokenizer.from_pretrained('roberta-large')\n",
          "except Exception:\n",
          "    tokenizer = AutoTokenizer.from_pretrained(HF_MODEL_NAME)\n",
          "\n",
          "processor = TrOCRProcessor(image_processor=image_processor, tokenizer=tokenizer)\n",
          "hf_model = VisionEncoderDecoderModel.from_pretrained(HF_MODEL_NAME).to(device)\n",
          "\n",
          "print('✅ Hugging Face TrOCR model loaded successfully into memory!')\n",
          "\n",
          "# 3. Alphanumeric license plate normalizer helper\n",
          "def normalize_plate(plate_str: str) -> str:\n",
          "    \"\"\"Removes spaces, hyphens, special symbols and standardizes to uppercase alphanumeric.\"\"\"\n",
          "    if not plate_str:\n",
          "        return ''\n",
          "    return re.sub(r'[^A-Z0-9]', '', str(plate_str).upper())\n",
          "\n",
          "print('Sample Plate Normalization: \"GJ 01 AB 1234\" ==> \"' + normalize_plate('GJ 01 AB 1234') + '\"')\n",
        ],
      },
      {
        cell_type: "markdown",
        metadata: { id: "step3_md" },
        source: [
          "## Step 3: Connect to Google Sheets Parking Registry\n",
          "Loads the company parking registry containing employee names, emails, car registration numbers, and assigned parking spots.",
        ],
      },
      {
        cell_type: "code",
        metadata: { id: "step3_code" },
        execution_count: null,
        outputs: [],
        source: [
          "# Google Sheet published CSV URL (File > Share > Publish to web > CSV):\n",
          "GOOGLE_SHEET_CSV_URL = 'https://docs.google.com/spreadsheets/d/YOUR_GOOGLE_SHEET_ID/export?format=csv'\n",
          "\n",
          "try:\n",
          "    df_parking = pd.read_csv(GOOGLE_SHEET_CSV_URL)\n",
          "    print('✅ Connected to live Google Sheet parking registry!')\n",
          "except Exception as e:\n",
          "    print('Using company parking dataset for demonstration...')\n",
          "    df_parking = pd.DataFrame([\n",
          "        {\n",
          "            'Name': 'Sanjay Rana',\n",
          "            'Email': 'sanjaysinh.rana@bacancy.com',\n",
          "            'PlateNumber': 'GJ 01 AB 1234',\n",
          "            'Department': 'Software Engineering',\n",
          "            'Phone': '+91 98765 43210',\n",
          "            'CarModel': 'White Hyundai i20',\n",
          "            'ParkingSpot': 'Bay #14'\n",
          "        },\n",
          "        {\n",
          "            'Name': 'Priya Patel',\n",
          "            'Email': 'priya.patel@bacancy.com',\n",
          "            'PlateNumber': 'GJ 27 BC 4590',\n",
          "            'Department': 'Product Management',\n",
          "            'Phone': '+91 98222 33445',\n",
          "            'CarModel': 'Silver Honda City',\n",
          "            'ParkingSpot': 'Bay #09'\n",
          "        },\n",
          "        {\n",
          "            'Name': 'Rahul Sharma',\n",
          "            'Email': 'rahul.sharma@bacancy.com',\n",
          "            'PlateNumber': 'MH 12 PQ 7890',\n",
          "            'Department': 'DevOps & Infra',\n",
          "            'Phone': '+91 99111 88223',\n",
          "            'CarModel': 'Red Tata Nexon',\n",
          "            'ParkingSpot': 'Bay #22'\n",
          "        },\n",
          "        {\n",
          "            'Name': 'Ananya Desai',\n",
          "            'Email': 'ananya.desai@bacancy.com',\n",
          "            'PlateNumber': 'DL 08 CA 3311',\n",
          "            'Department': 'Quality Assurance',\n",
          "            'Phone': '+91 97777 55443',\n",
          "            'CarModel': 'Blue Kia Seltos',\n",
          "            'ParkingSpot': 'Bay #04'\n",
          "        }\n",
          "    ])\n",
          "\n",
          "# Index normalized plate for fast lookups\n",
          "df_parking['NormalizedPlate'] = df_parking['PlateNumber'].apply(normalize_plate)\n",
          "display(df_parking[['Name', 'PlateNumber', 'Email', 'CarModel', 'ParkingSpot']])\n",
        ],
      },
      {
        cell_type: "markdown",
        metadata: { id: "step4_md" },
        source: [
          "## Step 4: Hugging Face TrOCR Plate Extraction & Colleague Matcher\n",
          "Runs the Hugging Face Transformer model on any vehicle image, extracts the plate text tokens, and matches against the parking database.",
        ],
      },
      {
        cell_type: "code",
        metadata: { id: "step4_code" },
        execution_count: null,
        outputs: [],
        source: [
          "import difflib\n",
          "\n",
          "def extract_plate_with_huggingface(image_input):\n",
          "    \"\"\"\n",
          "    Extracts vehicle license plate text using Hugging Face TrOCR.\n",
          "    Supports: file path, PIL.Image, or numpy array.\n",
          "    \"\"\"\n",
          "    if isinstance(image_input, str):\n",
          "        image = Image.open(image_input).convert('RGB')\n",
          "    elif not isinstance(image_input, Image.Image):\n",
          "        image = Image.fromarray(image_input).convert('RGB')\n",
          "    else:\n",
          "        image = image_input.convert('RGB')\n",
          "\n",
          "    # 1. Hugging Face processor converts image into pixel tensors\n",
          "    pixel_values = processor(image, return_tensors='pt').pixel_values.to(device)\n",
          "\n",
          "    # 2. VisionEncoderDecoder autoregressive generation\n",
          "    with torch.no_grad():\n",
          "        generated_ids = hf_model.generate(pixel_values)\n",
          "\n",
          "    # 3. Decode generated token IDs to string\n",
          "    raw_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]\n",
          "    clean_plate = normalize_plate(raw_text)\n",
          "    \n",
          "    return clean_plate, raw_text\n",
          "\n",
          "def match_colleague(plate_query, df_records):\n",
          "    \"\"\"Finds employee by exact, substring, or fuzzy similarity.\"\"\"\n",
          "    norm_query = normalize_plate(plate_query)\n",
          "    \n",
          "    # 1. Exact match\n",
          "    exact = df_records[df_records['NormalizedPlate'] == norm_query]\n",
          "    if not exact.empty:\n",
          "        return exact.iloc[0], 1.0, 'exact'\n",
          "        \n",
          "    # 2. Substring match (e.g. searching last 4 digits '1234' or 'AB1234')\n",
          "    sub = df_records[df_records['NormalizedPlate'].str.contains(norm_query, na=False)]\n",
          "    if not sub.empty:\n",
          "        return sub.iloc[0], 0.9, 'substring'\n",
          "        \n",
          "    # 3. Fuzzy similarity (handles OCR character ambiguities)\n",
          "    all_plates = df_records['NormalizedPlate'].tolist()\n",
          "    close = difflib.get_close_matches(norm_query, all_plates, n=1, cutoff=0.6)\n",
          "    if close:\n",
          "        match = df_records[df_records['NormalizedPlate'] == close[0]].iloc[0]\n",
          "        return match, 0.8, 'fuzzy'\n",
          "        \n",
          "    return None, 0.0, 'none'\n",
          "\n",
          "print('✅ Hugging Face TrOCR extraction and colleague matcher ready!')\n",
        ],
      },
      {
        cell_type: "markdown",
        metadata: { id: "step5_md" },
        source: [
          "## Step 5: Google Chat Deep Link Generator & Notification Dispatcher\n",
          "Creates the direct 1-click Google Chat DM link (`https://chat.google.com/dm/{email}`) with pre-formatted car move request.",
        ],
      },
      {
        cell_type: "code",
        metadata: { id: "step5_code" },
        execution_count: null,
        outputs: [],
        source: [
          "def create_google_chat_action(colleague, blocked_spot='Bay #14'):\n",
          "    \"\"\"Generates 1-click Google Chat DM link and drafted message.\"\"\"\n",
          "    first_name = str(colleague['Name']).split()[0]\n",
          "    email = colleague['Email']\n",
          "    plate = colleague['PlateNumber']\n",
          "    car = colleague.get('CarModel', 'vehicle')\n",
          "    \n",
          "    # Direct Google Chat DM Deep Link:\n",
          "    chat_url = f'https://chat.google.com/dm/{email}'\n",
          "    \n",
          "    message = (\n",
          "        f'Hi {first_name}, hope you are doing well! Your {car} ({plate}) is currently '\n",
          "        f'parked in {blocked_spot} and blocking another car. Could you please move it '\n",
          "        f'when you get a moment? Thank you!'\n",
          "    )\n",
          "    \n",
          "    print('====================================')\n",
          "    print('🎉 MATCH FOUND VIA HUGGING FACE MODEL!')\n",
          "    print(f'👤 Colleague: {colleague[\"Name\"]}')\n",
          "    print(f'📧 Email:     {email}')\n",
          "    print(f'🚗 Vehicle:   {car} ({plate})')\n",
          "    print(f'📍 Bay:       {blocked_spot}')\n",
          "    print('------------------------------------')\n",
          "    print(f'👉 Direct Google Chat Link:\\n{chat_url}')\n",
          "    print('------------------------------------')\n",
          "    print(f'📝 Draft Message:\\n\"{message}\"')\n",
          "    print('====================================')\n",
          "    \n",
          "    return {'chat_url': chat_url, 'message': message}\n",
          "\n",
          "# Test simulation with plate 'GJ 01 AB 1234':\n",
          "matched_emp, score, mtype = match_colleague('GJ 01 AB 1234', df_parking)\n",
          "if matched_emp is not None:\n",
          "    create_google_chat_action(matched_emp, blocked_spot='Bay #14')\n",
        ],
      },
      {
        cell_type: "markdown",
        metadata: { id: "step6_md" },
        source: [
          "## Step 6: Live Webcam Capture & Hugging Face End-to-End Pipeline\n",
          "Click the button in Google Colab to snap a live photo of a car plate with your webcam and process it through the Hugging Face model.",
        ],
      },
      {
        cell_type: "code",
        metadata: { id: "step6_code" },
        execution_count: null,
        outputs: [],
        source: [
          "from IPython.display import display, Javascript\n",
          "from google.colab.output import eval_js\n",
          "from base64 import b64decode\n",
          "\n",
          "def take_photo_colab(filename='parked_car.jpg', quality=0.85):\n",
          "    js = Javascript('''\n",
          "      async function takePhoto(quality) {\n",
          "        const div = document.createElement('div');\n",
          "        const capture = document.createElement('button');\n",
          "        capture.textContent = '📸 Snap Car Number Plate';\n",
          "        capture.style.cssText = 'padding: 10px 18px; background: #ea580c; color: white; border: none; border-radius: 8px; font-weight: bold; cursor: pointer; font-size: 14px;';\n",
          "        div.appendChild(capture);\n",
          "\n",
          "        const video = document.createElement('video');\n",
          "        video.style.display = 'block';\n",
          "        video.style.marginTop = '10px';\n",
          "        video.style.borderRadius = '8px';\n",
          "        const stream = await navigator.mediaDevices.getUserMedia({video: true});\n",
          "\n",
          "        document.body.appendChild(div);\n",
          "        div.appendChild(video);\n",
          "        video.srcObject = stream;\n",
          "        await video.play();\n",
          "\n",
          "        google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);\n",
          "        await new Promise((resolve) => capture.onclick = resolve);\n",
          "\n",
          "        const canvas = document.createElement('canvas');\n",
          "        canvas.width = video.videoWidth;\n",
          "        canvas.height = video.videoHeight;\n",
          "        canvas.getContext('2d').drawImage(video, 0, 0);\n",
          "        stream.getVideoTracks()[0].stop();\n",
          "        div.remove();\n",
          "        return canvas.toDataURL('image/jpeg', quality);\n",
          "      }\n",
          "    ''')\n",
          "    display(js)\n",
          "    data = eval_js('takePhoto({})'.format(quality))\n",
          "    binary = b64decode(data.split(',')[1])\n",
          "    with open(filename, 'wb') as f:\n",
          "        f.write(binary)\n",
          "    return filename\n",
          "\n",
          "print('Run `photo_path = take_photo_colab()` to snap a photo and run Hugging Face TrOCR!')\n",
        ],
      },
    ],
  };
};
